=== iiliev02/University/Projects/Cinema Project/Cinema/Cinema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cinema (cinemaName, contacts, staff, movies, food) >
<!ELEMENT cinemaName (#PCDATA) >
<!ELEMENT contacts (country, city, street, email, phone) >
<!ELEMENT country (#PCDATA) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT street (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT phone (#PCDATA) >
<!ELEMENT staff (employee+) >
<!ELEMENT employee (employeeName, employeeEmail, employeePhone, salary) >
<!ATTLIST employee id CDATA #REQUIRED >
<!ATTLIST employee job (Администратор|Разпоредител|Касиер|КафеСлужител) #REQUIRED >
<!ATTLIST employee gender (Мъж|Жена) #REQUIRED >
<!ELEMENT employeeName (#PCDATA) >
<!ELEMENT employeeEmail (#PCDATA) >
<!ELEMENT employeePhone (#PCDATA) >
<!ELEMENT salary (#PCDATA) >
<!ATTLIST salary currency CDATA #REQUIRED >
<!ELEMENT movies (movie+) >
<!ELEMENT movie (movieName, actors, movieDescription, duration, projections, hall, ticket) >
<!ATTLIST movie genre CDATA #REQUIRED >
<!ATTLIST movie category (2Д|3Д) #REQUIRED >
<!ELEMENT movieName (#PCDATA) >
<!ELEMENT actors (#PCDATA) >
<!ELEMENT movieDescription (#PCDATA) >
<!ELEMENT duration (#PCDATA) >
<!ELEMENT projections (#PCDATA) >
<!ELEMENT hall (#PCDATA) >
<!ELEMENT ticket (#PCDATA) >
<!ATTLIST ticket currency CDATA #REQUIRED >
<!ELEMENT food (offer+) >
<!ELEMENT offer (productName, quantity, price) >
<!ATTLIST offer type (Храна|Напитка) #REQUIRED >
<!ELEMENT productName (#PCDATA) >
<!ELEMENT quantity (#PCDATA) >
<!ELEMENT price (#PCDATA) >
<!ATTLIST price currency CDATA #REQUIRED >

=== iiliev02/University/Projects/Cinema Project/Cinema/Cinema_3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cinema SYSTEM "Cinema.dtd">
<cinema>
    <cinemaName>Кино Арена - Пловдив</cinemaName>
    <contacts>
        <country>България</country>
        <city>Пловдив</city>
        <street>бул. Руски 54</street>
        <email>kino_plovdiv@kinoarena.bg</email>
        <phone>02 4047 125</phone>
    </contacts>
    <staff>
        <employee id="1" job="Администратор" gender="Мъж">
            <employeeName>Койо Шишманов</employeeName>
            <employeeEmail>Kojo_Rushiev@abv.bg</employeeEmail>
            <employeePhone>0887 217 582</employeePhone>
            <salary currency="BGN">1600</salary>
        </employee>
        <employee id="2" job="Разпоредител" gender="Жена">
            <employeeName>Нона Рашкова</employeeName>
            <employeeEmail>Nona_Manuilova@gmail.bg</employeeEmail>
            <employeePhone>0887 082 185</employeePhone>
            <salary currency="BGN">1300</salary>
        </employee>
        <employee id="3" job="Касиер" gender="Мъж">
            <employeeName>Ангелко Сватомиров</employeeName>
            <employeeEmail>Angelko_Svatomirov@yahoo.bg</employeeEmail>
            <employeePhone>0887 064 725</employeePhone>
            <salary currency="BGN">1050</salary>
        </employee>
        <employee id="4" job="КафеСлужител" gender="Мъж">
            <employeeName>Бенислав Преславов</employeeName>
            <employeeEmail>BenislavPejev@abv.bg</employeeEmail>
            <employeePhone>0888 858 805</employeePhone>
            <salary currency="BGN">1050</salary>
        </employee>
    </staff>
    <movies>
        <movie genre="Драма" category="2Д">
            <movieName>Петя на моята Петя</movieName>
            <actors>
                Александра Костова, Алиса Атанасова, Албена Павлова, Юлиан Вергов, Моньо Монев,
                Алена Вергова, Ясен Атанасов, Мартин Методиев, Емил Марков, Александър Милчев
            </actors>
            <movieDescription>
                Коя е Петя?
                Новата учебна година започва с внезапни промени. Нов директор, нови правила и тежък инцидент,
                който ще промени живота на група младежи от 11ти клас. На фона на несправедливостта в гимназията,
                едно момиче решава да действа и да се бори срещу всичко, което превръща съучениците ѝ „в консервни кутии без етикети“.
                Защото системата в лицето на директор Крачунов обича послушните и не толерира различните.
                40 години след смъртта на любимата ѝ поетеса Петя Дубарова, Петя ще открие смисъла в това да живее и обича истински.
            </movieDescription>
            <duration>95 минути</duration>
            <projections>13:00, 15:15, 17:15, 19:15, 21:15</projections>
            <hall>2</hall>
            <ticket currency="BGN">10</ticket>
        </movie>
        <movie genre="Ужаси" category="2Д">
            <movieName>Писък</movieName>
            <actors>
                Нев Кембъл, Кортни Кокс, Дейвид Аркет, Джак Куейд, Марли Шелтън, Мелиса Барера, Джена Ортега, Дилън Минет
            </actors>
            <movieDescription>
                25 години след като поредица от брутални убийства шокира жителите на малкото и спокойно градче Уудсбъро,
                нов убиец надява емблематичната маска на Гоустфейс и започва да избива група тийнейджъри,
                възкресявайки тайни от смъртоносното минало на града. Ветераните от няколко сблъсъка с
                различни проявления на безмилостния Гоустфейс Сидни Прескот, Гейл Уедърс и Дюи Райли се
                събират отново в опит да разкрият мистерията и да спасят младежите и себе си преди да е
                станало твърде късно. Този път обаче има нещо различно – правилата на играта за оцеляване са вече други...
            </movieDescription>
            <duration>116 минути</duration>
            <projections>19:45, 21:45</projections>
            <hall>1</hall>
            <ticket currency="BGN">7</ticket>
        </movie>
        <movie genre="Екшън" category="2Д">
            <movieName>The King's Man: Първа Мисия</movieName>
            <actors>
                Ралф Файнс, Джема Артъртън, Рис Ифанс, Харис Дикинсън, Джимон Унсу, Матю Гууд, Том Холандър, Даниел Брюл, Чарлс Данс
            </actors>
            <movieDescription>
                King's Man: Първа мисия ни връща към корените на първата независима шпионска агенция,
                работеща на най-високо ниво на дискретност и чиято нестандартна дейност е едновременно
                изискана и брутална, цивилизована и безмилостна. Когато най-безскрупулните злодеи и
                престъпни гении в историята, сред които Распутин, Мата Хари, Ерик Ян Ханусен и Вилхелм II,
                се събират, за да планират война, която да избие милиони хора, съдбата на света пада върху
                плещите на млад джентълмен, който влиза в надпревара с времето, за да предотврати драматичния
                изход от събитията.
            </movieDescription>
            <duration>131 минути</duration>
            <projections>20:30</projections>
            <hall>3</hall>
            <ticket currency="BGN">9</ticket>
        </movie>
        <movie genre="Фантастика" category="3Д">
            <movieName>Спайдърмен: Няма път към дома</movieName>
            <actors>
                Зендая, Том Холанд, Бенедикт Къмбърбач, Мариса Томей, Джейми Фокс, Ангури Райс
            </actors>
            <movieDescription>
                Питър Паркър е свалил маската и вече не може да раздели нормалния си живот от този на супергерой.
                Когато моли за помощ Доктор Стрейндж, залогът става още по-опасен.
                Питър ще разбере какво наистина означава да си Спайдърмен.
            </movieDescription>
            <duration>150 минути</duration>
            <projections>15:00</projections>
            <hall>2</hall>
            <ticket currency="BGN">10</ticket>
        </movie>
    </movies>
    <food>
        <offer type="Храна">
            <productName>Пуканки</productName>
            <quantity>Средни</quantity>
            <price currency="BGN">4.99</price>
        </offer>
        <offer type="Храна">
            <productName>Пуканки</productName>
            <quantity>Големи</quantity>
            <price currency="BGN">5.99</price>
        </offer>
        <offer type="Напитка">
            <productName>Спрайт</productName>
            <quantity>500мл.</quantity>
            <price currency="BGN">6.99</price>
        </offer>
        <offer type="Напитка">
            <productName>Спрайт</productName>
            <quantity>750мл.</quantity>
            <price currency="BGN">7.99</price>
        </offer>
    </food>
</cinema>
