=== iiliev02/University/Projects/Cinema Project/Cinema/Cinema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cinema (cinemaName, contacts, staff, movies, food) >
<!ELEMENT cinemaName (#PCDATA) >
<!ELEMENT contacts (country, city, street, email, phone) >
<!ELEMENT country (#PCDATA) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT street (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT phone (#PCDATA) >
<!ELEMENT staff (employee+) >
<!ELEMENT employee (employeeName, employeeEmail, employeePhone, salary) >
<!ATTLIST employee id CDATA #REQUIRED >
<!ATTLIST employee job (Администратор|Разпоредител|Касиер|КафеСлужител) #REQUIRED >
<!ATTLIST employee gender (Мъж|Жена) #REQUIRED >
<!ELEMENT employeeName (#PCDATA) >
<!ELEMENT employeeEmail (#PCDATA) >
<!ELEMENT employeePhone (#PCDATA) >
<!ELEMENT salary (#PCDATA) >
<!ATTLIST salary currency CDATA #REQUIRED >
<!ELEMENT movies (movie+) >
<!ELEMENT movie (movieName, actors, movieDescription, duration, projections, hall, ticket) >
<!ATTLIST movie genre CDATA #REQUIRED >
<!ATTLIST movie category (2Д|3Д) #REQUIRED >
<!ELEMENT movieName (#PCDATA) >
<!ELEMENT actors (#PCDATA) >
<!ELEMENT movieDescription (#PCDATA) >
<!ELEMENT duration (#PCDATA) >
<!ELEMENT projections (#PCDATA) >
<!ELEMENT hall (#PCDATA) >
<!ELEMENT ticket (#PCDATA) >
<!ATTLIST ticket currency CDATA #REQUIRED >
<!ELEMENT food (offer+) >
<!ELEMENT offer (productName, quantity, price) >
<!ATTLIST offer type (Храна|Напитка) #REQUIRED >
<!ELEMENT productName (#PCDATA) >
<!ELEMENT quantity (#PCDATA) >
<!ELEMENT price (#PCDATA) >
<!ATTLIST price currency CDATA #REQUIRED >

=== iiliev02/University/Projects/Cinema Project/Cinema/Cinema_5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cinema SYSTEM "Cinema.dtd">
<cinema>
    <cinemaName>Кино Арена - София</cinemaName>
    <contacts>
        <country>България</country>
        <city>София</city>
        <street>бул. Цариградско шосе 115</street>
        <email>kino_sofia@kinoarena.bg</email>
        <phone>02 4047 121</phone>
    </contacts>
    <staff>
        <employee id="1" job="Администратор" gender="Мъж">
            <employeeName>Мартиниян Хитков</employeeName>
            <employeeEmail>MartiniqnPachev@abv.bg</employeeEmail>
            <employeePhone>0888 404 769</employeePhone>
            <salary currency="BGN">2000</salary>
        </employee>
        <employee id="2" job="Разпоредител" gender="Мъж">
            <employeeName>Траян Демиров</employeeName>
            <employeeEmail>TraqnGalinov@gmail.bg</employeeEmail>
            <employeePhone>0887 446 196</employeePhone>
            <salary currency="BGN">1600</salary>
        </employee>
        <employee id="3" job="Касиер" gender="Жена">
            <employeeName>Аурора Руменова</employeeName>
            <employeeEmail>AuroraNonkova@yahoo.bg</employeeEmail>
            <employeePhone>0887 960 735</employeePhone>
            <salary currency="BGN">1300</salary>
        </employee>
        <employee id="4" job="КафеСлужител" gender="Жена">
            <employeeName>Цеца Манолова</employeeName>
            <employeeEmail>CecaKycieva@abv.bg</employeeEmail>
            <employeePhone>0887 534 083</employeePhone>
            <salary currency="BGN">1300</salary>
        </employee>
    </staff>
    <movies>
        <movie genre="Фантастика" category="3Д">
            <movieName>Спайдърмен: Няма път към дома</movieName>
            <actors>
                Зендая, Том Холанд, Бенедикт Къмбърбач, Мариса Томей, Джейми Фокс, Ангури Райс
            </actors>
            <movieDescription>
                Питър Паркър е свалил маската и вече не може да раздели нормалния си живот от този на супергерой.
                Когато моли за помощ Доктор Стрейндж, залогът става още по-опасен.
                Питър ще разбере какво наистина означава да си Спайдърмен.
            </movieDescription>
            <duration>150 минути</duration>
            <projections>15:00, 16:30, 20:15</projections>
            <hall>2</hall>
            <ticket currency="BGN">11</ticket>
        </movie>
        <movie genre="Фантастика" category="3Д">
            <movieName>Дюн</movieName>
            <actors>
                Тимъти Шаламe, Оскар Айзък, Ребека Фъргюсън, Зендея, Джейсън Момоа, Стелан Скарсгард, Дейв Батиста, Хавиер Бардем, Джош Бролин
            </actors>
            <movieDescription>
                Потомък на благородната династия Атреиди търси възмездие за смъртта на баща си,
                като в същото време е призван да защитава планетата на подправките Аракис, известна още като Дюн.
                Именно там се намира най-ценният ресурс, който може да отключи страховития потенциалн на човечеството.
                Но само тези, които могат да преборят най-големите си страхове, ще оцелеят.
            </movieDescription>
            <duration>155 минути</duration>
            <projections>16:30</projections>
            <hall>1</hall>
            <ticket currency="BGN">10</ticket>
        </movie>
        <movie genre="Екшън" category="2Д">
            <movieName>Матрицата: Възкресение</movieName>
            <actors>
                Киану Рийвс, Приянка Чопра, Джейда Пинкет Смит, Джонатан Гроф, Джесика Хенуик,
                Яхия Абдул-Матийн ІІ, Кари-Ан Мос
            </actors>
            <movieDescription>
                Продължение на историята обединява кинематографичните икони Neo And Trinity,
                докато се впускат обратно в Матрицата и още по -дълбоко в заешката дупка.
                Съкрушително ново приключение с екшън и епичен мащаб, то е разположено в познат,
                но още по-провокативен свят, където реалността е по-субективна от всякога.
                Всичко, което е необходимо, за да се види истината, е да освободите ума си.
            </movieDescription>
            <duration>155 минути</duration>
            <projections>13:15, 18:15, 21:15</projections>
            <hall>3</hall>
            <ticket currency="BGN">9</ticket>
        </movie>
        <movie genre="Мистерии" category="2Д">
            <movieName>Улицата на кошмарите</movieName>
            <actors>Брадли Купър, Кейт Бланшет, Руни Мара и Тони Колет</actors>
            <movieDescription>
                Улицата на кошмарите е адаптация на едноименния роман на Уилям Линдзи Грешам от 1946 година
                и разказва за Стантън Карлайл (Брадли Купър) – бивш карнавален работник,
                който се превръща в една от топ атракциите в нощните клубове на големия град.
                Чрез различни трикове, които заимства от своята колежка Моли (Тони Колет),
                както и с помощта на приятелката си Зийна (Руни Мара), Стантън създава впечатлението,
                че е могъщ медиум, способен да чете умовете на хората. Първоначално идеята е просто да
                впечатлява и забавлява тълпата на карнавала, но стремежът към слава и богатство става
                причина представлението да  се превърне в средство за финансови измами,
                чиято цел са по-заможните жители на града. Така Стантън попада в полезрението на
                психиатъра д-р Лилит Ритър (Кейт Бланшет), която се опитва да
                го изобличи като шарлатанин, но впоследствие става част от схемите му.
            </movieDescription>
            <duration>150 минути</duration>
            <projections>13:30, 16:00, 19:45, 21:30</projections>
            <hall>4</hall>
            <ticket currency="BGN">10</ticket>
        </movie>
    </movies>
    <food>
        <offer type="Храна">
            <productName>Пуканки</productName>
            <quantity>Средни</quantity>
            <price currency="BGN">6.99</price>
        </offer>
        <offer type="Храна">
            <productName>Пуканки</productName>
            <quantity>Големи</quantity>
            <price currency="BGN">8.99</price>
        </offer>
        <offer type="Храна">
            <productName>Начос</productName>
            <quantity>500гр.</quantity>
            <price currency="BGN">8.99</price>
        </offer>
        <offer type="Напитка">
            <productName>Кола</productName>
            <quantity>500мл.</quantity>
            <price currency="BGN">7.99</price>
        </offer>
        <offer type="Напитка">
            <productName>Кола</productName>
            <quantity>750мл.</quantity>
            <price currency="BGN">8.99</price>
        </offer>
    </food>
</cinema>

=== iiliev02/University/Projects/Cinema Project/Cinema/Cinema_4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cinema SYSTEM "Cinema.dtd">
<cinema>
    <cinemaName>Кино Арена - Плевен</cinemaName>
    <contacts>
        <country>България</country>
        <city>Плевен</city>
        <street>пл. Иван Миндиликов 1</street>
        <email>kino_pleven@kinoarena.bg</email>
        <phone>02 4047 129</phone>
    </contacts>
    <staff>
        <employee id="1" job="Администратор" gender="Жена">
            <employeeName>Анастасия Събилянова</employeeName>
            <employeeEmail>AnastasiqKazimirova@abv.bg</employeeEmail>
            <employeePhone>0887 282 986</employeePhone>
            <salary currency="BGN">1250</salary>
        </employee>
        <employee id="2" job="Разпоредител" gender="Жена">
            <employeeName>Розанка Славолюбова</employeeName>
            <employeeEmail>Rozanka_Dobrqnova@gmail.bg</employeeEmail>
            <employeePhone>0889 771 625</employeePhone>
            <salary currency="BGN">1050</salary>
        </employee>
        <employee id="3" job="Касиер" gender="Жена">
            <employeeName>Дамяна Николчева</employeeName>
            <employeeEmail>DamqnaKazimirova@yahoo.bg</employeeEmail>
            <employeePhone>0888 096 646</employeePhone>
            <salary currency="BGN">850</salary>
        </employee>
        <employee id="4" job="КафеСлужител" gender="Жена">
            <employeeName>Хриса Кирякева Раянова</employeeName>
            <employeeEmail>HrisaKirqkeva@abv.bg</employeeEmail>
            <employeePhone>0889 478 964</employeePhone>
            <salary currency="BGN">850</salary>
        </employee>
    </staff>
    <movies>
        <movie genre="Анимация" category="2Д">
            <movieName>Горските мечоци: Див Свят</movieName>
            <actors>
                Крис Бойки, Ники Стинсон, Тан Хао, Занг Уеи, Бингжун Занг
            </actors>
            <movieDescription>
                Вълнуващ нов увеселителен парк отваря врати в Пайн Трий.
                „Див Свят“ предлага невиждана досега атракция!
                С помощта на революционно откритие в генетиката всеки може да се превърне в диво животно!
                И да изживее емоцията на дивия свят по неповторим начин.
                Освен това всеки може да участва в състезание с награда от един милион долара!
                Вик и любимите ни Горски мечоци решават да се включат в състезанието като отбор заедно с Брембъл,
                Реймънд и мистериозния Леон. И изненадващо дори за самите тях те печелят!
                Но с това започват и истинските изпитания!
                Защото Леон има тайна мисия, Брембъл преследва свои цели, а собственикът на „Див Свят“
                Том не само е направил откритие в генетиката, но и е нарушил всички закони и морални норми.
            </movieDescription>
            <duration>99 минути</duration>
            <projections>11:00, 12:00, 13:15, 15:30</projections>
            <hall>2</hall>
            <ticket currency="BGN">7</ticket>
        </movie>
        <movie genre="Анимация" category="2Д">
            <movieName>Клифърд: Голямото червено куче</movieName>
            <actors>
                Дарби Камп, Сиена Гилори, Джак Уайтхол, Джон Клийз
            </actors>
            <movieDescription>
                Докато Емили се мъчи да се впише у дома и в училище, тя открива малко червено кученце,
                което е предопределено да стане най -добрият й приятел. Само че кучето е необикновено....
            </movieDescription>
            <duration>97 минути</duration>
            <projections>14:15</projections>
            <hall>1</hall>
            <ticket currency="BGN">7</ticket>
        </movie>
        <movie genre="Анимация" category="2Д">
            <movieName>Ела, изпей 2</movieName>
            <actors>
                Тарон Егертън, Матю Макконъхи, Скарлет Йохансон
            </actors>
            <movieDescription>
                Продължение на световния попкултурен феномен на Illumination, Ела, изпей! 2 отново ни среща с предприемчивата,
                оптимистично настроена коала Бъстър Муун и неговия звезден състав от колоритни музикални изпълнители,
                които ще стартират най-ослепителната си феерия до момента. Има само една уловка: първо трябва да
                убедят най-известната рокзвезда на света, отказала се от сцената и живееща в пълно усамотение,
                да се присъедини към тях.
            </movieDescription>
            <duration>108 минути</duration>
            <projections>12:30</projections>
            <hall>3</hall>
            <ticket currency="BGN">7</ticket>
        </movie>
        <movie genre="Фантастика" category="3Д">
            <movieName>Спайдърмен: Няма път към дома</movieName>
            <actors>
                Зендая, Том Холанд, Бенедикт Къмбърбач, Мариса Томей, Джейми Фокс, Ангури Райс
            </actors>
            <movieDescription>
                Питър Паркър е свалил маската и вече не може да раздели нормалния си живот от този на супергерой.
                Когато моли за помощ Доктор Стрейндж, залогът става още по-опасен.
                Питър ще разбере какво наистина означава да си Спайдърмен.
            </movieDescription>
            <duration>150 минути</duration>
            <projections>15:00</projections>
            <hall>Vip</hall>
            <ticket currency="BGN">10</ticket>
        </movie>
    </movies>
    <food>
        <offer type="Храна">
            <productName>Пуканки</productName>
            <quantity>Средни</quantity>
            <price currency="BGN">4.99</price>
        </offer>
        <offer type="Храна">
            <productName>Пуканки</productName>
            <quantity>Големи</quantity>
            <price currency="BGN">5.99</price>
        </offer>
        <offer type="Напитка">
            <productName>Кола</productName>
            <quantity>500мл.</quantity>
            <price currency="BGN">5.99</price>
        </offer>
        <offer type="Напитка">
            <productName>Кола</productName>
            <quantity>750мл.</quantity>
            <price currency="BGN">6.99</price>
        </offer>
    </food>
</cinema>

=== iiliev02/University/Project/Cinema Project/Cinema/Cinema_2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cinema SYSTEM "Cinema.dtd">
<cinema>
    <cinemaName>Кино Арена - Бургас</cinemaName>
    <contacts>
        <country>България</country>
        <city>Бургас</city>
        <street>бул. България 69</street>
        <email>kino_burgas@kinoarena.bg</email>
        <phone>02 4047 123</phone>
    </contacts>
    <staff>
        <employee id="1" job="Администратор" gender="Жена">
            <employeeName>Росица Танова</employeeName>
            <employeeEmail>RosicaVuleva@abv.bg</employeeEmail>
            <employeePhone>0888 001 802</employeePhone>
            <salary currency="BGN">1500</salary>
        </employee>
        <employee id="2" job="Разпоредител" gender="Жена">
            <employeeName>Ивет Тимонова</employeeName>
            <employeeEmail>IvetGodislavova@gmail.bg</employeeEmail>
            <employeePhone>0889 921 940</employeePhone>
            <salary currency="BGN">1200</salary>
        </employee>
        <employee id="3" job="Касиер" gender="Мъж">
            <employeeName>Тихослав Светланов</employeeName>
            <employeeEmail>Tihoslav_Karlov@yahoo.bg</employeeEmail>
            <employeePhone>0889 810 501</employeePhone>
            <salary currency="BGN">950</salary>
        </employee>
        <employee id="4" job="КафеСлужител" gender="Мъж">
            <employeeName>Николай Филиев</employeeName>
            <employeeEmail>Nikolaj_Teodorov@abv.bg</employeeEmail>
            <employeePhone>0888 107 896</employeePhone>
            <salary currency="BGN">950</salary>
        </employee>
    </staff>
    <movies>
        <movie genre="Драма" category="2Д">
            <movieName>Петя на моята Петя</movieName>
            <actors>
                Александра Костова, Алиса Атанасова, Албена Павлова, Юлиан Вергов, Моньо Монев,
                Алена Вергова, Ясен Атанасов, Мартин Методиев, Емил Марков, Александър Милчев
            </actors>
            <movieDescription>
                Коя е Петя?
                Новата учебна година започва с внезапни промени. Нов директор, нови правила и тежък инцидент,
                който ще промени живота на група младежи от 11ти клас. На фона на несправедливостта в гимназията,
                едно момиче решава да действа и да се бори срещу всичко, което превръща съучениците ѝ „в консервни кутии без етикети“.
                Защото системата в лицето на директор Крачунов обича послушните и не толерира различните.
                40 години след смъртта на любимата ѝ поетеса Петя Дубарова, Петя ще открие смисъла в това да живее и обича истински.
            </movieDescription>
            <duration>95 минути</duration>
            <projections>11:00, 13:25, 16:00, 18:00, 20:00, 22:00</projections>
            <hall>2</hall>
            <ticket currency="BGN">10</ticket>
        </movie>
        <movie genre="Ужаси" category="2Д">
            <movieName>Писък</movieName>
            <actors>
                Нев Кембъл, Кортни Кокс, Дейвид Аркет, Джак Куейд, Марли Шелтън, Мелиса Барера, Джена Ортега, Дилън Минет
            </actors>
            <movieDescription>
                25 години след като поредица от брутални убийства шокира жителите на малкото и спокойно градче Уудсбъро,
                нов убиец надява емблематичната маска на Гоустфейс и започва да избива група тийнейджъри,
                възкресявайки тайни от смъртоносното минало на града. Ветераните от няколко сблъсъка с
                различни проявления на безмилостния Гоустфейс Сидни Прескот, Гейл Уедърс и Дюи Райли се
                събират отново в опит да разкрият мистерията и да спасят младежите и себе си преди да е
                станало твърде късно. Този път обаче има нещо различно – правилата на играта за оцеляване са вече други...
            </movieDescription>
            <duration>116 минути</duration>
            <projections>18:30, 21:00</projections>
            <hall>1</hall>
            <ticket currency="BGN">7</ticket>
        </movie>
        <movie genre="Екшън" category="2Д">
            <movieName>The King's Man: Първа Мисия</movieName>
            <actors>
                Ралф Файнс, Джема Артъртън, Рис Ифанс, Харис Дикинсън, Джимон Унсу, Матю Гууд, Том Холандър, Даниел Брюл, Чарлс Данс
            </actors>
            <movieDescription>
                King's Man: Първа мисия ни връща към корените на първата независима шпионска агенция,
                работеща на най-високо ниво на дискретност и чиято нестандартна дейност е едновременно
                изискана и брутална, цивилизована и безмилостна. Когато най-безскрупулните злодеи и
                престъпни гении в историята, сред които Распутин, Мата Хари, Ерик Ян Ханусен и Вилхелм II,
                се събират, за да планират война, която да избие милиони хора, съдбата на света пада върху
                плещите на млад джентълмен, който влиза в надпревара с времето, за да предотврати драматичния
                изход от събитията.
            </movieDescription>
            <duration>131 минути</duration>
            <projections>13:00, 20:00, 21:15</projections>
            <hall>3</hall>
            <ticket currency="BGN">9</ticket>
        </movie>
        <movie genre="Криминален" category="2Д">
            <movieName>Домът на Gucci</movieName>
            <actors>
                Адам Драйвър, Лейди Гага, Джереми Айрънс, Ал Пачино, Джаред Лето
            </actors>
            <movieDescription>
                Вдъхновен от шокиращата истинска история на империята зад италианската модна къща Gucci,
                филмът ще разкрие на зрителите какво означава да носиш това име, каква е неговата цена и
                колко далеч би стигнало едно семейство, за да получи контрол и власт. Ще станем свидетели
                на три десетилетия, изпълнени с любов, упадък, амбиция, предателства и отмъщение,
                водещи до трагичен край – убийство.
            </movieDescription>
            <duration>158 минути</duration>
            <projections>19:45</projections>
            <hall>4</hall>
            <ticket currency="BGN">11</ticket>
        </movie>
    </movies>
    <food>
        <offer type="Храна">
            <productName>Пуканки</productName>
            <quantity>Средни</quantity>
            <price currency="BGN">4.99</price>
        </offer>
        <offer type="Храна">
            <productName>Пуканки</productName>
            <quantity>Големи</quantity>
            <price currency="BGN">5.99</price>
        </offer>
        <offer type="Напитка">
            <productName>Фанта</productName>
            <quantity>500мл.</quantity>
            <price currency="BGN">6.99</price>
        </offer>
        <offer type="Напитка">
            <productName>Фанта</productName>
            <quantity>750мл.</quantity>
            <price currency="BGN">7.99</price>
        </offer>
    </food>
</cinema>

=== iiliev02/University/Projects/Cinema Project/Cinema/test.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cinema SYSTEM "Cinema.dtd">
<cinema>
    <cinemaName>Кино Арена - Варна</cinemaName>
    <contacts>
        <country>България</country>
        <city>Варна</city>
        <street>ул. Акад. Андрей Сахаров</street>
        <email>kino_varna@kinoarena.bg</email>
        <phone>02 4047 133</phone>
    </contacts>
    <staff>
        <employee id="1" gender="Мъж" job="Касиер">
            <employeeName>Христо Иванов</employeeName>
            <employeeEmail>VasoGechev@abv.bg</employeeEmail>
            <employeePhone>0888 848 323</employeePhone>
            <salary currency="BGN">1800</salary>
        </employee>
        <employee id="2" gender="Жена" job="Разпоредител">
            <employeeName>Карина Цецкова</employeeName>
            <employeeEmail>Karina_Snejanova@gmail.bg</employeeEmail>
            <employeePhone>0887 358 627</employeePhone>
            <salary currency="BGN">1300</salary>
        </employee>
        <employee id="3" gender="Жена" job="Касиер">
            <employeeName>Сийка Теодославова</employeeName>
            <employeeEmail>SijkaValentinova@yahoo.bg</employeeEmail>
            <employeePhone>0889 096 875</employeePhone>
            <salary currency="BGN">1150</salary>
        </employee>
        <employee id="4" gender="Жена" job="КафеСлужител">
            <employeeName>Мариела Янова</employeeName>
            <employeeEmail>MarielaRozalinova@abv.bg</employeeEmail>
            <employeePhone>0888 768 598</employeePhone>
            <salary currency="BGN">1150</salary>
        </employee>
    </staff>
    <movies>
        <movie genre="Фантастика" category="3Д">
            <movieName>Спайдърмен: Няма път към дома</movieName>
            <actors>
                Зендая, Том Холанд, Бенедикт Къмбърбач, Мариса Томей, Джейми Фокс, Ангури Райс
            </actors>
            <movieDescription>
                Питър Паркър е свалил маската и вече не може да раздели нормалния си живот от този на супергерой.
                Когато моли за помощ Доктор Стрейндж, залогът става още по-опасен.
                Питър ще разбере какво наистина означава да си Спайдърмен.
            </movieDescription>
            <duration>150 минути</duration>
            <projections>15:00, 16:30, 20:15</projections>
            <hall>2</hall>
            <ticket currency="BGN">11</ticket>
        </movie>
        <movie genre="Екшън" category="2Д">
            <movieName>Матрицата: Възкресение</movieName>
            <actors>
                Киану Рийвс, Приянка Чопра, Джейда Пинкет Смит, Джонатан Гроф, Джесика Хенуик, Яхия Абдул-Матийн ІІ, Кари-Ан Мос
            </actors>
            <movieDescription>
                Продължение на историята обединява кинематографичните икони Neo And Trinity,
                докато се впускат обратно в Матрицата и още по -дълбоко в заешката дупка.
                Съкрушително ново приключение с екшън и епичен мащаб, то е разположено в познат,
                но още по-провокативен свят, където реалността е по-субективна от всякога.
                Всичко, което е необходимо, за да се види истината, е да освободите ума си.
            </movieDescription>
            <duration>155 минути</duration>
            <projections>13:15, 18:15, 21:15</projections>
            <hall>3</hall>
            <ticket currency="BGN">9</ticket>
        </movie>
        <movie genre="Комедия" category="2Д">
            <movieName>Бай Иван: Филмът</movieName>
            <actors>
                Димитър Кирязов, Силвия Йорданова
            </actors>
            <movieDescription>
                Филмът е базиран на изключително популярния образ Бай Иван от Youtube канала “Светът на Ванката”.
            </movieDescription>
            <duration>95 минути</duration>
            <projections>14:15, 19:00</projections>
            <hall>1</hall>
            <ticket currency="BGN">9</ticket>
        </movie>
        <movie genre="Мистерии" category="2Д">
            <movieName>Улицата на кошмарите</movieName>
            <actors>
                Брадли Купър, Кейт Бланшет, Руни Мара и Тони Колет
            </actors>
            <movieDescription>
                Улицата на кошмарите е адаптация на едноименния роман на Уилям Линдзи Грешам от 1946 година
                и разказва за Стантън Карлайл (Брадли Купър) – бивш карнавален работник,
                който се превръща в една от топ атракциите в нощните клубове на големия град.
                Чрез различни трикове, които заимства от своята колежка Моли (Тони Колет),
                както и с помощта на приятелката си Зийна (Руни Мара), Стантън създава впечатлението,
                че е могъщ медиум, способен да чете умовете на хората. Първоначално идеята е просто да
                впечатлява и забавлява тълпата на карнавала, но стремежът към слава и богатство става
                причина представлението да  се превърне в средство за финансови измами,
                чиято цел са по-заможните жители на града. Така Стантън попада в полезрението на
                психиатъра д-р Лилит Ритър (Кейт Бланшет), която се опитва да
                го изобличи като шарлатанин, но впоследствие става част от схемите му.
            </movieDescription>
            <duration>150 минути</duration>
            <projections>14:30, 17:45, 20:45</projections>
            <hall>4</hall>
            <ticket currency="BGN">9</ticket>
        </movie>
    </movies>
    <food>
        <offer type="Храна">
            <productName>Пуканки</productName>
            <quantity>Средни</quantity>
            <price currency="BGN">5.99</price>
        </offer>
        <offer type="Храна">
            <productName>Пуканки</productName>
            <quantity>Големи</quantity>
            <price currency="BGN">7.99</price>
        </offer>
        <offer type="Храна">
            <productName>Начос</productName>
            <quantity>500гр</quantity>
            <price currency="BGN">7.99</price>
        </offer>
        <offer type="Напитка">
            <productName>Кола</productName>
            <quantity>500мл.</quantity>
            <price currency="BGN">6.99</price>
        </offer>
        <offer type="Напитка">
            <productName>Кола</productName>
            <quantity>750мл.</quantity>
            <price currency="BGN">8.99</price>
        </offer>
    </food>
</cinema>
